export const SHOW_MODAL_LOGIN = "SHOW_MODAL_LOGIN"
export const SHOW_MODAL_SIGNUP = "SHOW_MODAL_SIGNUP"
export const PROPERTY_VIEW = "PROPERTY_VIEW"
export const ADD_PROPERTY_VIEW = "ADD_PROPERTY_VIEW"